package com.navi.portfolio;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.text.DecimalFormat;
import java.util.*;
import java.util.regex.*;

public class HomeActivity extends Activity {
    static final int REQ_IMPORT=7, REQ_EXPORT=8;
    static final int NAVY=Color.rgb(20,38,70), BLUE=Color.rgb(45,105,210), GREEN=Color.rgb(0,145,110), BG=Color.rgb(242,246,252), TXT=Color.rgb(30,35,45), SUB=Color.rgb(100,110,125), RED=Color.rgb(210,45,45), LOSS=Color.rgb(25,118,210);
    static final String KRW="KRW", USD="USD";
    ArrayList<Item> items=new ArrayList<Item>();
    DecimalFormat won=new DecimalFormat("#,###"), usd=new DecimalFormat("#,##0.00");
    LinearLayout root, body; boolean dash=true; String display=KRW; double fx=1400;
    Spinner accountSpin, currencySpin, stockSpin; TextView vValue,vCost,vPnl,vRate,vFx,vTarget,vRebal; EditText fxEdit; Chart chart; TableLayout table;
    Stock[] stocks={new Stock("CASH","현금",KRW),new Stock("005930.KS","삼성전자",KRW),new Stock("000660.KS","SK하이닉스",KRW),new Stock("035420.KS","NAVER",KRW),new Stock("005380.KS","현대차",KRW),new Stock("069500.KS","KODEX 200",KRW),new Stock("360750.KS","TIGER 미국S&P500",KRW),new Stock("133690.KS","TIGER 미국나스닥100",KRW),new Stock("AAPL","Apple",USD),new Stock("MSFT","Microsoft",USD),new Stock("NVDA","NVIDIA",USD),new Stock("GOOGL","Alphabet",USD),new Stock("AMZN","Amazon",USD),new Stock("META","Meta",USD),new Stock("TSLA","Tesla",USD),new Stock("VOO","Vanguard S&P500",USD),new Stock("QQQ","Invesco QQQ",USD),new Stock("SCHD","Schwab Dividend",USD),new Stock("TLT","20Y Treasury",USD),new Stock("GLD","Gold ETF",USD)};

    static class Stock { String code,name,cur; Stock(String c,String n,String u){code=c;name=n;cur=u;} String label(){return name+"  /  "+code+"  /  "+cur;} }
    static class Item { String account,code,name,cur,memo; double qty,buy,now,target; Item(String a,String c,String n,double q,double b,double p,String u,double t,String m){account=a;code=c;name=n;qty=q;buy=b;now=p;cur=u;target=t;memo=m==null?"":m;} double cost(){return qty*buy;} double value(){return qty*now;} double pnl(){return value()-cost();} double rate(){return cost()==0?0:pnl()/cost()*100;} }

    public void onCreate(Bundle b){super.onCreate(b); load(); if(items.size()==0) sample(); build(); render();}

    void build(){ScrollView sv=new ScrollView(this); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG); sv.addView(root); setContentView(sv); header(); body=new LinearLayout(this); body.setOrientation(LinearLayout.VERTICAL); body.setPadding(dp(14),dp(12),dp(14),dp(26)); root.addView(body);}
    void header(){LinearLayout h=new LinearLayout(this); h.setOrientation(LinearLayout.VERTICAL); h.setPadding(dp(18),dp(20),dp(18),dp(14)); h.setBackgroundColor(NAVY); root.addView(h); h.addView(tv("자산 포트폴리오",27,Color.WHITE,true)); TextView sub=tv("현재가 · 환율 · 목표비중 · AI 추천",13,Color.rgb(210,220,240),false); sub.setPadding(0,dp(3),0,dp(12)); h.addView(sub); LinearLayout tabs=new LinearLayout(this); tabs.setOrientation(LinearLayout.HORIZONTAL); h.addView(tabs); Button b1=tab("대시보드",true), b2=tab("설정/관리",false); b1.setOnClickListener(new View.OnClickListener(){public void onClick(View v){dash=true; render();}}); b2.setOnClickListener(new View.OnClickListener(){public void onClick(View v){dash=false; render();}}); tabs.addView(b1,new LinearLayout.LayoutParams(0,dp(44),1)); tabs.addView(b2,new LinearLayout.LayoutParams(0,dp(44),1));}
    Button tab(String s,boolean on){Button b=new Button(this); b.setText(s); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setTextSize(15); b.setBackground(round(on?BLUE:Color.rgb(54,70,105),18)); return b;}
    void render(){body.removeAllViews(); if(dash) dashboard(); else settings();}

    void dashboard(){body.addView(tv("사용자 대시보드",22,TXT,true)); TextView d=tv("계좌별 자산, 수익률, 목표비중 대비 조정 금액을 봅니다.",12,SUB,false); d.setPadding(0,dp(4),0,dp(10)); body.addView(d); accountSpin=new Spinner(this); body.addView(accountSpin,new LinearLayout.LayoutParams(-1,dp(48))); setupAccounts(); vValue=metric("평가금액"); vCost=metric("매입금액"); vPnl=metric("손익"); vRate=metric("수익률"); vFx=metric("적용 환율"); vTarget=metric("목표비중 합계"); vRebal=metric("리밸런싱 요약"); chart=new Chart(this); chart.setBackground(round(Color.WHITE,24)); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(410)); cp.setMargins(0,dp(10),0,dp(12)); body.addView(chart,cp); body.addView(tv("보유 종목",20,TXT,true)); HorizontalScrollView hs=new HorizontalScrollView(this); table=new TableLayout(this); hs.addView(table); LinearLayout box=card(); box.addView(hs); body.addView(box); refresh();}
    TextView metric(String label){LinearLayout c=card(); c.addView(tv(label,12,SUB,false)); TextView v=tv("-",23,TXT,true); c.addView(v); body.addView(c); return v;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.VERTICAL); c.setPadding(dp(14),dp(12),dp(14),dp(12)); c.setBackground(round(Color.WHITE,22)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,dp(8),0,0); c.setLayoutParams(lp); return c;}

    void settings(){body.addView(tv("설정/관리",22,TXT,true)); TextView d=tv("통화, 환율, 현재가, 종목, 목표비중, AI 추천을 관리합니다.",12,SUB,false); d.setPadding(0,dp(4),0,dp(10)); body.addView(d); LinearLayout c=card(); c.addView(tv("표시통화와 환율",15,TXT,true)); currencySpin=new Spinner(this); ArrayAdapter<String> ca=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,new String[]{KRW,USD}); ca.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); currencySpin.setAdapter(ca); currencySpin.setSelection(USD.equals(display)?1:0); c.addView(currencySpin,new LinearLayout.LayoutParams(-1,dp(48))); fxEdit=input("USD/KRW 환율",true); fxEdit.setText(usd.format(fx)); c.addView(fxEdit); addBtn(c,"환율 적용",BLUE,new View.OnClickListener(){public void onClick(View v){double n=num(fxEdit); if(n>0)fx=n; display=currencySpin.getSelectedItem().toString(); save(); toast("적용했습니다");}}); body.addView(c); addBtn(body,"현재가/환율 자동 갱신",BLUE,new View.OnClickListener(){public void onClick(View v){refreshMarket();}}); addBtn(body,"종목 선택 추가",BLUE,new View.OnClickListener(){public void onClick(View v){addDialog();}}); addBtn(body,"비율/자금분배 조정",GREEN,new View.OnClickListener(){public void onClick(View v){allocDialog();}}); addBtn(body,"AI 요청문 복사",GREEN,new View.OnClickListener(){public void onClick(View v){copyPrompt();}}); addBtn(body,"AI 추천 붙여넣기 적용",GREEN,new View.OnClickListener(){public void onClick(View v){aiDialog();}}); addBtn(body,"미래에셋 CSV 가져오기",BLUE,new View.OnClickListener(){public void onClick(View v){importCsv();}}); addBtn(body,"CSV 내보내기",BLUE,new View.OnClickListener(){public void onClick(View v){exportCsv();}}); addBtn(body,"전체 초기화",LOSS,new View.OnClickListener(){public void onClick(View v){reset();}}); TextView g=tv("종목은 목록에서 선택하면 티커와 통화가 자동 연결됩니다. AI 답변은 '티커 / 목표비중% / 자금분배시기' 형식을 권장합니다.",12,SUB,false); g.setPadding(0,dp(12),0,0); body.addView(g);}
    void addBtn(LinearLayout p,String s,int color,View.OnClickListener l){Button b=new Button(this); b.setText(s); b.setAllCaps(false); b.setTextSize(15); b.setTextColor(Color.WHITE); b.setBackground(round(color,18)); b.setOnClickListener(l); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50)); lp.setMargins(0,dp(8),0,0); p.addView(b,lp);}

    void setupAccounts(){LinkedHashSet<String> set=new LinkedHashSet<String>(); set.add("전체"); for(Item it:items)set.add(clean(it.account)); ArrayList<String> arr=new ArrayList<String>(set); ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,arr); ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); accountSpin.setAdapter(ad); accountSpin.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){refresh();} public void onNothingSelected(android.widget.AdapterView<?> p){refresh();}});}
    ArrayList<Item> filtered(){String a=accountSpin==null||accountSpin.getSelectedItem()==null?"전체":accountSpin.getSelectedItem().toString(); ArrayList<Item> out=new ArrayList<Item>(); for(Item it:items)if("전체".equals(a)||a.equals(clean(it.account)))out.add(it); return out;}
    void refresh(){if(vValue==null)return; ArrayList<Item> list=filtered(); double cost=0,val=0,target=0; for(Item it:list){cost+=disp(it.cost(),it.cur); val+=disp(it.value(),it.cur); target+=Math.max(0,it.target);} double pnl=val-cost, rate=cost==0?0:pnl/cost*100; vValue.setText(money(val)); vCost.setText(money(cost)); vPnl.setText((pnl>=0?"+":"")+money(pnl)); vPnl.setTextColor(pnl>=0?RED:LOSS); vRate.setText(String.format(Locale.KOREA,"%+.2f%%",rate)); vRate.setTextColor(rate>=0?RED:LOSS); vFx.setText("1달러 = "+won.format(fx)+"원"); vTarget.setText(target>0?String.format(Locale.KOREA,"%.1f%%",target):"목표비중 미설정"); vRebal.setText(rebal(list,val)); if(chart!=null){chart.display=display; chart.fx=fx; chart.setData(list);} drawTable(list,val);}
    String rebal(ArrayList<Item> list,double total){double buy=0,sell=0; if(total<=0)return "데이터 없음"; for(Item it:list)if(it.target>0){double diff=total*it.target/100-disp(it.value(),it.cur); if(diff>0)buy+=diff; else sell+=-diff;} return buy+sell==0?"목표비중을 설정하면 계산됩니다":"추가매수 "+money(buy)+" / 축소 "+money(sell);}
    void drawTable(ArrayList<Item> list,double total){if(table==null)return; table.removeAllViews(); String[] h={"계좌","티커","종목","통화","수량","현재가","평가","손익","현재%","목표%","조정","분배시기","삭제"}; TableRow head=new TableRow(this); for(String x:h)cell(head,x,true,TXT); table.addView(head); for(final Item it:list){TableRow r=new TableRow(this); double v=disp(it.value(),it.cur), p=disp(it.pnl(),it.cur), pct=total==0?0:v/total*100, adj=it.target>0?total*it.target/100-v:0; cell(r,clean(it.account),false,TXT); cell(r,it.code,false,TXT); cell(r,it.name,false,TXT); cell(r,it.cur,false,TXT); cell(r,plain(it.qty),false,TXT); cell(r,price(it.now,it.cur),false,TXT); cell(r,money(v),false,TXT); cell(r,(p>=0?"+":"")+money(p),false,p>=0?RED:LOSS); cell(r,String.format(Locale.KOREA,"%.1f%%",pct),false,TXT); cell(r,it.target>0?String.format(Locale.KOREA,"%.1f%%",it.target):"-",false,TXT); cell(r,it.target>0?(adj>=0?"+":"")+money(adj):"-",false,adj>=0?RED:LOSS); cell(r,shorten(it.memo),false,TXT); Button del=new Button(this); del.setText("삭제"); del.setOnClickListener(new View.OnClickListener(){public void onClick(View v){items.remove(it); save(); render();}}); r.addView(del); table.addView(r);}}
    void cell(TableRow r,String s,boolean bold,int color){TextView v=tv(s==null?"":s,bold?13:12,color,bold); v.setMinWidth(dp(82)); v.setPadding(dp(7),dp(8),dp(7),dp(8)); r.addView(v);}

    void addDialog(){LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); final EditText acc=input("계좌명 예: ISA",false); stockSpin=new Spinner(this); ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_item,stockLabels()); ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); stockSpin.setAdapter(ad); final TextView info=tv(stocks[0].label(),13,TXT,true); final EditText qty=input("수량",true), buy=input("평균매입가",true), now=input("현재가",true), target=input("목표비중 %",true), memo=input("자금분배시기 메모",false); memo.setSingleLine(false); memo.setMinLines(2); stockSpin.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){Stock st=stocks[pos]; info.setText(st.label()); if("CASH".equals(st.code)){now.setText("1"); if(buy.length()==0)buy.setText("1");}} public void onNothingSelected(android.widget.AdapterView<?> p){}}); box.addView(acc); box.addView(stockSpin,new LinearLayout.LayoutParams(-1,dp(48))); box.addView(info); box.addView(qty); box.addView(buy); box.addView(now); box.addView(target); box.addView(memo); Button price=new Button(this); price.setText("선택 종목 현재가 가져오기"); price.setOnClickListener(new View.OnClickListener(){public void onClick(View v){fetchOne(stocks[stockSpin.getSelectedItemPosition()],now,buy);}}); box.addView(price); new AlertDialog.Builder(this).setTitle("종목 선택 추가").setView(box).setPositiveButton("저장",new android.content.DialogInterface.OnClickListener(){public void onClick(android.content.DialogInterface d,int w){Stock st=stocks[stockSpin.getSelectedItemPosition()]; double n=num(now), b=num(buy); if(b==0&&n>0)b=n; items.add(new Item(val(acc,"기본계좌"),st.code,st.name,num(qty),b,n,st.cur,num(target),val(memo,""))); save(); render();}}).setNegativeButton("취소",null).show();}
    void fetchOne(final Stock st,final EditText now,final EditText buy){if("CASH".equals(st.code)){now.setText("1"); return;} toast("조회 중"); new Thread(new Runnable(){public void run(){final double p=fetchPrice(st.code); runOnUiThread(new Runnable(){public void run(){if(p>0){now.setText(plain(p)); if(buy.length()==0)buy.setText(plain(p)); toast("현재가 반영");}else toast("조회 실패");}});}}).start();}
    void allocDialog(){ScrollView sv=new ScrollView(this); LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); sv.addView(box); final ArrayList<EditText> ps=new ArrayList<EditText>(), ms=new ArrayList<EditText>(); for(Item it:items){box.addView(tv(it.name+" / "+it.code,14,TXT,true)); EditText p=input("목표비중 %",true); if(it.target>0)p.setText(plain(it.target)); EditText m=input("자금분배시기",false); m.setSingleLine(false); m.setMinLines(2); m.setText(it.memo); box.addView(p); box.addView(m); ps.add(p); ms.add(m);} new AlertDialog.Builder(this).setTitle("비율/자금분배 조정").setView(sv).setPositiveButton("저장",new android.content.DialogInterface.OnClickListener(){public void onClick(android.content.DialogInterface d,int w){for(int i=0;i<items.size();i++){items.get(i).target=num(ps.get(i)); items.get(i).memo=ms.get(i).getText().toString().trim();} save(); render();}}).setNegativeButton("취소",null).show();}
    void aiDialog(){LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); box.addView(tv("AI 답변 예: AAPL / 25% / 지금 30%, 조정 시 40%",12,SUB,false)); final EditText e=input("AI 추천 내용",false); e.setSingleLine(false); e.setMinLines(9); box.addView(e); new AlertDialog.Builder(this).setTitle("AI 추천 적용").setView(box).setPositiveButton("적용",new android.content.DialogInterface.OnClickListener(){public void onClick(android.content.DialogInterface d,int w){applyAi(e.getText().toString());}}).setNegativeButton("취소",null).show();}
    void applyAi(String text){int n=0; for(String line:text.split("\\n")){double pct=percent(line); Stock st=findStock(line); if(pct<0||st==null)continue; Item it=findItem(st.code); if(it==null){items.add(new Item("AI추천",st.code,st.name,0,0,"CASH".equals(st.code)?1:0,st.cur,pct,line));} else {it.target=pct; it.memo=line; it.name=st.name; it.cur=st.cur;} n++;} save(); render(); toast(n+"개 항목 반영");}
    void copyPrompt(){StringBuilder sb=new StringBuilder(); sb.append("아래 포트폴리오를 목표비중과 자금분배시기로 재구성해 줘. 각 줄은 티커 / 목표비중% / 자금분배시기 형식.\n"); double total=0; for(Item it:items)total+=disp(it.value(),it.cur); for(Item it:items)sb.append(it.code).append(" / ").append(it.name).append(" / 현재비중 ").append(total==0?"0%":String.format(Locale.KOREA,"%.1f%%",disp(it.value(),it.cur)/total*100)).append("\n"); ((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("AI portfolio prompt",sb.toString())); toast("AI 요청문 복사 완료");}

    void refreshMarket(){toast("현재가와 환율 갱신 중"); new Thread(new Runnable(){public void run(){int ok=0; double f=fetchFx(); if(f>0)fx=f; for(Item it:items){if("CASH".equals(it.code))continue; double p=fetchPrice(it.code); if(p>0){it.now=p; if(it.buy==0)it.buy=p; ok++;}} final int count=ok; runOnUiThread(new Runnable(){public void run(){save(); render(); toast("갱신 완료: "+count+"개");}});}}).start();}
    double fetchFx(){try{JSONObject r=new JSONObject(fetch("https://open.er-api.com/v6/latest/USD")).getJSONObject("rates"); return r.optDouble("KRW",0);}catch(Exception e){return 0;}}
    double fetchPrice(String symbol){try{String u="https://query1.finance.yahoo.com/v8/finance/chart/"+URLEncoder.encode(symbol,"UTF-8")+"?range=1d&interval=1d"; JSONObject meta=new JSONObject(fetch(u)).getJSONObject("chart").getJSONArray("result").getJSONObject(0).getJSONObject("meta"); double p=meta.optDouble("regularMarketPrice",0); return p>0?p:meta.optDouble("previousClose",0);}catch(Exception e){return 0;}}
    String fetch(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection(); c.setConnectTimeout(8000); c.setReadTimeout(8000); c.setRequestProperty("User-Agent","Mozilla/5.0"); BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8")); StringBuilder sb=new StringBuilder(); String line; while((line=br.readLine())!=null)sb.append(line); br.close(); return sb.toString();}

    void importCsv(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("*/*"); startActivityForResult(i,REQ_IMPORT);} void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("text/csv"); i.putExtra(Intent.EXTRA_TITLE,"portfolio.csv"); startActivityForResult(i,REQ_EXPORT);} public void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data); if(res!=RESULT_OK||data==null||data.getData()==null)return; try{if(req==REQ_IMPORT){parseCsv(data.getData()); save(); render(); toast("CSV 가져오기 완료");}else if(req==REQ_EXPORT){OutputStream o=getContentResolver().openOutputStream(data.getData()); o.write(csv().getBytes("UTF-8")); o.close(); toast("CSV 저장 완료");}}catch(Exception e){toast("처리 실패: "+e.getMessage());}}
    void parseCsv(Uri uri)throws Exception{BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(uri),"UTF-8")); ArrayList<String[]> rows=new ArrayList<String[]>(); String line; while((line=br.readLine())!=null)if(line.trim().length()>0)rows.add(split(line)); br.close(); if(rows.size()==0)return; int start=0,acc=0,code=1,name=2,qty=3,buy=4,now=5,cur=-1,target=-1,memo=-1; if(join(rows.get(0)).contains("종목")||join(rows.get(0)).toLowerCase(Locale.ROOT).contains("account")){String[] h=rows.get(0); acc=find(h,"계좌","account"); code=find(h,"종목코드","코드","ticker","symbol"); name=find(h,"종목명","이름","name"); qty=find(h,"수량","qty"); buy=find(h,"평균","평단","매입","buy"); now=find(h,"현재","price","now"); cur=findOpt(h,"통화","currency"); target=findOpt(h,"목표","target"); memo=findOpt(h,"분배","memo","plan"); start=1;} items.clear(); for(int i=start;i<rows.size();i++){String[] r=rows.get(i); String c=get(r,code,""), n=get(r,name,c); if(c.length()==0&&n.length()==0)continue; items.add(new Item(get(r,acc,"기본계좌"),c,n,number(get(r,qty,"0")),number(get(r,buy,"0")),number(get(r,now,"0")),get(r,cur,infer(c)),number(get(r,target,"0")),get(r,memo,"")));}}
    String csv(){StringBuilder sb=new StringBuilder("계좌,종목코드,종목명,통화,수량,평균매입가,현재가,평가금액,손익,수익률,목표비중,분배시기\n"); for(Item it:items)sb.append(q(it.account)).append(',').append(q(it.code)).append(',').append(q(it.name)).append(',').append(q(it.cur)).append(',').append(it.qty).append(',').append(it.buy).append(',').append(it.now).append(',').append(disp(it.value(),it.cur)).append(',').append(disp(it.pnl(),it.cur)).append(',').append(it.rate()).append(',').append(it.target).append(',').append(q(it.memo)).append('\n'); return sb.toString();}
    String[] split(String line){ArrayList<String> out=new ArrayList<String>(); StringBuilder sb=new StringBuilder(); boolean q=false; for(int i=0;i<line.length();i++){char c=line.charAt(i); if(c=='\"')q=!q; else if(c==','&&!q){out.add(sb.toString().trim()); sb.setLength(0);} else sb.append(c);} out.add(sb.toString().trim()); return out.toArray(new String[0]);}

    void save(){try{JSONArray a=new JSONArray(); for(Item it:items){JSONObject o=new JSONObject(); o.put("a",it.account); o.put("c",it.code); o.put("n",it.name); o.put("u",it.cur); o.put("q",it.qty); o.put("b",it.buy); o.put("p",it.now); o.put("t",it.target); o.put("m",it.memo); a.put(o);} getSharedPreferences("data",0).edit().putString("items",a.toString()).putString("display",display).putFloat("fx",(float)fx).apply();}catch(Exception e){}}
    void load(){try{SharedPreferences sp=getSharedPreferences("data",0); display=sp.getString("display",KRW); fx=sp.getFloat("fx",1400f); JSONArray a=new JSONArray(sp.getString("items","[]")); for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i); items.add(new Item(o.optString("a"),o.optString("c"),o.optString("n"),o.optDouble("q"),o.optDouble("b"),o.optDouble("p"),o.optString("u",infer(o.optString("c"))),o.optDouble("t"),o.optString("m")));}}catch(Exception e){}}
    void sample(){items.add(new Item("ISA","005930.KS","삼성전자",10,70000,72500,KRW,30,"조정 시 분할")); items.add(new Item("연금","360750.KS","TIGER 미국S&P500",20,20000,21000,KRW,25,"월 1회 적립")); items.add(new Item("해외","AAPL","Apple",2,180,192,USD,25,"환율 하락 시 추가")); items.add(new Item("현금","CASH","현금",1000000,1,1,KRW,20,"예비자금"));}
    void reset(){new AlertDialog.Builder(this).setTitle("전체 초기화").setMessage("모든 종목을 삭제할까요?").setPositiveButton("삭제",new android.content.DialogInterface.OnClickListener(){public void onClick(android.content.DialogInterface d,int w){items.clear(); save(); render();}}).setNegativeButton("취소",null).show();}

    TextView tv(String s,int size,int color,boolean bold){TextView v=new TextView(this); v.setText(s); v.setTextSize(size); v.setTextColor(color); if(bold)v.setTypeface(null,1); return v;} EditText input(String hint,boolean num){EditText e=new EditText(this); e.setHint(hint); if(num)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED); return e;} GradientDrawable round(int color,int rad){GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(rad)); return g;} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    double num(EditText e){return number(e.getText().toString());} double number(String s){try{return Double.parseDouble(s.replace(",","").replace("원","").replace("₩","").replace("$","").replace("%","").trim());}catch(Exception e){return 0;}} String val(EditText e,String f){String s=e.getText().toString().trim(); return s.length()==0?f:s;} String money(double x){return USD.equals(display)?"$"+usd.format(x):won.format(Math.round(x))+"원";} String price(double x,String u){return USD.equals(u)?"$"+usd.format(x):won.format(Math.round(x))+"원";} double disp(double x,String u){if(u==null)u=KRW; if(u.equals(display))return x; if(USD.equals(u)&&KRW.equals(display))return x*fx; if(KRW.equals(u)&&USD.equals(display))return fx<=0?x:x/fx; return x;} String plain(double d){return d==Math.rint(d)?String.valueOf((long)d):String.format(Locale.US,"%.4f",d).replaceAll("0+$","").replaceAll("\\.$","");} String clean(String s){return s==null||s.trim().length()==0?"기본계좌":s.trim();} String shorten(String s){if(s==null||s.trim().length()==0)return "-"; s=s.replace('\n',' '); return s.length()>24?s.substring(0,24)+"…":s;} String q(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}
    String[] stockLabels(){String[] a=new String[stocks.length]; for(int i=0;i<stocks.length;i++)a[i]=stocks[i].label(); return a;} String norm(String s){return s==null?"":s.toUpperCase(Locale.ROOT).replace(" ","").replace(".","").replace("-","").replace("/","");} Stock findStock(String line){String n=norm(line); for(Stock st:stocks)if(n.contains(norm(st.code))||n.contains(norm(st.name)))return st; return null;} Item findItem(String code){String n=norm(code); for(Item it:items)if(norm(it.code).equals(n))return it; return null;} double percent(String s){Matcher m=Pattern.compile("(\\d+(?:\\.\\d+)?)\\s*%").matcher(s); return m.find()?number(m.group(1)):-1;} String infer(String c){if(c==null)return KRW; c=c.toUpperCase(Locale.ROOT); return c.endsWith(".KS")||c.endsWith(".KQ")||c.matches("\\d{6}")||"CASH".equals(c)?KRW:USD;} int find(String[] h,String...k){int x=findOpt(h,k); return x>=0?x:0;} int findOpt(String[] h,String...k){for(int i=0;i<h.length;i++){String s=h[i].replace(" ","").toLowerCase(Locale.ROOT); for(String kk:k)if(s.contains(kk.toLowerCase(Locale.ROOT)))return i;} return -1;} String get(String[] a,int i,String f){return i>=0&&i<a.length&&a[i].trim().length()>0?a[i].trim():f;} String join(String[] a){StringBuilder b=new StringBuilder(); for(String s:a)b.append(s); return b.toString();}

    public static class Chart extends View { Paint p=new Paint(1); ArrayList<Item> data=new ArrayList<Item>(); String display=KRW; double fx=1400; int[] colors={Color.rgb(66,133,244),Color.rgb(251,188,5),Color.rgb(52,168,83),Color.rgb(156,39,176),Color.rgb(0,150,136),Color.rgb(255,112,67)}; public Chart(Context c){super(c);} public void setData(ArrayList<Item> d){data.clear(); data.addAll(d); invalidate();} protected void onDraw(Canvas c){int w=getWidth(),h=getHeight(); p.setColor(Color.WHITE); c.drawRect(0,0,w,h,p); p.setColor(TXT); p.setTextSize(30); p.setFakeBoldText(true); c.drawText("자산 비중",24,44,p); p.setFakeBoldText(false); double total=0; for(Item it:data)total+=Math.max(0,val(it)); if(total<=0){p.setColor(SUB); c.drawText("데이터 없음",30,95,p); return;} float cx=w*.28f, cy=h*.30f, r=Math.min(w,h)*.18f, start=-90; RectF oval=new RectF(cx-r,cy-r,cx+r,cy+r); for(int i=0;i<data.size();i++){float sw=(float)(Math.max(0,val(data.get(i)))/total*360); p.setColor(colors[i%colors.length]); c.drawArc(oval,start,sw,true,p); start+=sw;} p.setColor(Color.WHITE); c.drawCircle(cx,cy,r*.58f,p); p.setTextSize(18); int y=78; for(int i=0;i<Math.min(data.size(),6);i++){Item it=data.get(i); p.setColor(colors[i%colors.length]); c.drawRect(w*.56f,y-16,w*.56f+22,y+5,p); p.setColor(Color.rgb(70,75,85)); c.drawText(shortName(it.name)+" "+String.format(Locale.KOREA,"%.1f%%",val(it)/total*100),w*.56f+30,y+3,p); y+=30;} float top=h*.62f, base=h-52, left=34, right=w-34; p.setTextSize(28); p.setColor(TXT); p.setFakeBoldText(true); c.drawText("종목별 손익",24,top-18,p); p.setFakeBoldText(false); double max=1; for(Item it:data)max=Math.max(max,Math.abs(pnl(it))); int n=Math.min(data.size(),8); if(n==0)return; float gap=8,bw=(right-left-gap*(n-1))/n; p.setColor(Color.rgb(225,229,236)); c.drawLine(left,base,right,base,p); for(int i=0;i<n;i++){Item it=data.get(i); float bh=(float)(Math.abs(pnl(it))/max*(h*.20f)), x0=left+i*(bw+gap); p.setColor(pnl(it)>=0?RED:LOSS); c.drawRect(x0,base-bh,x0+bw,base,p); p.setColor(Color.rgb(70,75,85)); p.setTextSize(16); c.drawText(shortName(it.name),x0,base+24,p);}} double val(Item it){double x=it.value(); if(it.cur.equals(display))return x; if(USD.equals(it.cur)&&KRW.equals(display))return x*fx; if(KRW.equals(it.cur)&&USD.equals(display))return x/fx; return x;} double pnl(Item it){double x=it.pnl(); if(it.cur.equals(display))return x; if(USD.equals(it.cur)&&KRW.equals(display))return x*fx; if(KRW.equals(it.cur)&&USD.equals(display))return x/fx; return x;} static String shortName(String s){return s==null?"":s.length()>5?s.substring(0,5):s;} }
}
