package com.navi.portfolio;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.text.DecimalFormat;
import java.util.*;
import java.util.regex.*;

public class MainActivity extends Activity {
    static final int REQ_IMPORT=1001, REQ_EXPORT=1002;
    static final int NAVY=Color.rgb(22,38,68), BLUE=Color.rgb(43,104,205), GREEN=Color.rgb(0,145,110), BG=Color.rgb(242,246,252), CARD=Color.WHITE, TEXT=Color.rgb(30,35,45), MUTED=Color.rgb(105,113,128), RED=Color.rgb(211,47,47), LOSS=Color.rgb(25,118,210);
    static final String KRW="KRW", USD="USD", CASH="CASH";
    static final Stock[] CATALOG={
        new Stock("CASH","현금",KRW),new Stock("005930.KS","삼성전자",KRW),new Stock("000660.KS","SK하이닉스",KRW),new Stock("035420.KS","NAVER",KRW),new Stock("035720.KS","카카오",KRW),new Stock("005380.KS","현대차",KRW),new Stock("000270.KS","기아",KRW),new Stock("373220.KS","LG에너지솔루션",KRW),new Stock("207940.KS","삼성바이오로직스",KRW),new Stock("005490.KS","POSCO홀딩스",KRW),new Stock("068270.KS","셀트리온",KRW),new Stock("105560.KS","KB금융",KRW),new Stock("069500.KS","KODEX 200",KRW),new Stock("360750.KS","TIGER 미국S&P500",KRW),new Stock("379810.KS","KODEX 미국NASDAQ100TR",KRW),new Stock("133690.KS","TIGER 미국나스닥100",KRW),
        new Stock("AAPL","Apple",USD),new Stock("MSFT","Microsoft",USD),new Stock("NVDA","NVIDIA",USD),new Stock("GOOGL","Alphabet",USD),new Stock("AMZN","Amazon",USD),new Stock("META","Meta",USD),new Stock("TSLA","Tesla",USD),new Stock("AVGO","Broadcom",USD),new Stock("JPM","JPMorgan",USD),new Stock("VOO","Vanguard S&P 500 ETF",USD),new Stock("SPY","SPDR S&P 500 ETF",USD),new Stock("QQQ","Invesco QQQ",USD),new Stock("SCHD","Schwab Dividend ETF",USD),new Stock("TLT","iShares 20+ Treasury",USD),new Stock("GLD","SPDR Gold Shares",USD),new Stock("VTI","Vanguard Total Stock",USD)
    };
    ArrayList<Holding> holdings=new ArrayList<>();
    DecimalFormat won=new DecimalFormat("#,###"), dollar=new DecimalFormat("#,##0.00");
    LinearLayout root, body; Spinner accountSpin, currencySpin; TextView valueView,costView,pnlView,rateView,fxView,targetView,rebalanceView; Chart chart; TableLayout table; EditText fxInput; String displayCurrency=KRW; double usdKrw=1400; boolean dashboard=true;

    static class Stock{String code,name,cur; Stock(String c,String n,String u){code=c;name=n;cur=u;} String label(){return name+"   " +code+"   "+cur;}}
    static class Holding{String account,code,name,cur,memo; double qty,buy,now,target; Holding(String a,String c,String n,double q,double b,double p,String u,double t,String m){account=a;code=c;name=n;qty=q;buy=b;now=p;cur=(u==null||u.length()==0)?infer(c):u;target=t;memo=m==null?"":m;} double cost(){return qty*buy;} double value(){return qty*now;} double pnl(){return value()-cost();} double rate(){return cost()==0?0:pnl()/cost()*100;}}

    public void onCreate(Bundle b){super.onCreate(b); loadSettings(); loadData(); if(holdings.isEmpty()) sample(); build(); render();}

    void build(){ScrollView s=new ScrollView(this); root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(BG); s.addView(root); setContentView(s); header(); body=new LinearLayout(this); body.setOrientation(LinearLayout.VERTICAL); body.setPadding(dp(14),dp(12),dp(14),dp(24)); root.addView(body);}
    void header(){LinearLayout h=new LinearLayout(this); h.setOrientation(LinearLayout.VERTICAL); h.setPadding(dp(18),dp(18),dp(18),dp(14)); h.setBackgroundColor(NAVY); root.addView(h,new LinearLayout.LayoutParams(-1,-2)); TextView t=txt("자산 포트폴리오",26,Color.WHITE,true); h.addView(t); TextView sub=txt("현재가 · 환율 · 목표비중 · AI 추천 적용",13,Color.rgb(205,216,235),false); sub.setPadding(0,dp(4),0,dp(12)); h.addView(sub); LinearLayout tabs=new LinearLayout(this); tabs.setOrientation(LinearLayout.HORIZONTAL); h.addView(tabs); Button d=tab("대시보드",true), m=tab("설정/관리",false); d.setOnClickListener(v->{dashboard=true;render();}); m.setOnClickListener(v->{dashboard=false;render();}); tabs.addView(d,new LinearLayout.LayoutParams(0,dp(44),1)); tabs.addView(m,new LinearLayout.LayoutParams(0,dp(44),1));}
    Button tab(String s,boolean on){Button b=new Button(this); b.setText(s); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setTextSize(15); b.setBackground(bg(on?BLUE:Color.rgb(45,60,92),18)); return b;}
    void render(){if(body==null)return; body.removeAllViews(); if(dashboard) dashboard(); else settings();}

    void dashboard(){TextView title=txt("사용자 대시보드",22,TEXT,true); body.addView(title); TextView desc=txt("계좌와 표시통화를 선택하면 전체 자산과 리밸런싱 금액이 자동 계산됩니다.",12,MUTED,false); desc.setPadding(0,dp(3),0,dp(10)); body.addView(desc); accountSpin=new Spinner(this); body.addView(accountSpin,new LinearLayout.LayoutParams(-1,dp(48))); setupAccounts(); valueView=metric("평가금액"); costView=metric("매입금액"); pnlView=metric("손익"); rateView=metric("수익률"); fxView=metric("적용 환율"); targetView=metric("목표비중 합계"); rebalanceView=metric("리밸런싱 요약"); chart=new Chart(this); chart.setBackground(bg(CARD,24)); LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(430)); cp.setMargins(0,dp(10),0,dp(12)); body.addView(chart,cp); TextView list=txt("보유 종목",20,TEXT,true); list.setPadding(0,dp(8),0,dp(6)); body.addView(list); HorizontalScrollView hsv=new HorizontalScrollView(this); table=new TableLayout(this); hsv.addView(table); LinearLayout wrap=card(); wrap.addView(hsv); body.addView(wrap); refreshNumbers();}
    TextView metric(String label){LinearLayout c=card(); TextView l=txt(label,12,MUTED,false); TextView v=txt("-",23,TEXT,true); c.addView(l); c.addView(v); body.addView(c); return v;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this); c.setOrientation(LinearLayout.VERTICAL); c.setPadding(dp(14),dp(12),dp(14),dp(12)); c.setBackground(bg(CARD,22)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2); lp.setMargins(0,dp(8),0,0); c.setLayoutParams(lp); return c;}

    void settings(){TextView title=txt("설정/관리",22,TEXT,true); body.addView(title); TextView desc=txt("통화, 환율, 현재가, 종목, 목표비중, AI 추천을 이 화면에서 관리합니다.",12,MUTED,false); desc.setPadding(0,dp(3),0,dp(10)); body.addView(desc); LinearLayout c=card(); body.addView(c); TextView l=txt("표시통화와 환율",15,TEXT,true); c.addView(l); currencySpin=new Spinner(this); ArrayAdapter<String> ca=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,new String[]{KRW,USD}); ca.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); currencySpin.setAdapter(ca); currencySpin.setSelection(USD.equals(displayCurrency)?1:0); c.addView(currencySpin,new LinearLayout.LayoutParams(-1,dp(48))); fxInput=input("USD/KRW 환율",true); fxInput.setText(dollar.format(usdKrw)); c.addView(fxInput); currencySpin.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){displayCurrency=pos==1?USD:KRW; saveSettings();} public void onNothingSelected(android.widget.AdapterView<?> p){}}); addAction(c,"환율 적용",v->{double f=num(fxInput); if(f>0)usdKrw=f; saveSettings(); toast("환율을 적용했습니다");}); addAction(body,"현재가/환율 자동 갱신",v->refreshMarket()); addAction(body,"종목 선택 추가",v->addDialog()); addAction(body,"비율/자금분배 조정",v->allocationDialog()); addAction(body,"AI 요청문 복사",v->copyAiPrompt()); addAction(body,"AI 추천 붙여넣기 적용",v->aiDialog()); addAction(body,"미래에셋 CSV 가져오기",v->importCsv()); addAction(body,"CSV 내보내기",v->exportCsv()); addAction(body,"전체 초기화",v->confirmReset()); TextView g=txt("종목은 목록에서 선택하면 티커와 통화가 자동으로 연결됩니다. AI 추천은 '티커 또는 종목명 / 목표비중% / 자금분배시기' 형식이면 자동 반영됩니다.",12,MUTED,false); g.setPadding(0,dp(12),0,0); body.addView(g);}
    void addAction(LinearLayout parent,String label,View.OnClickListener l){Button b=new Button(this); b.setText(label); b.setAllCaps(false); b.setTextColor(Color.WHITE); b.setTextSize(15); b.setBackground(bg(label.contains("초기화")?LOSS:(label.contains("AI")?GREEN:BLUE),18)); b.setOnClickListener(l); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50)); lp.setMargins(0,dp(8),0,0); parent.addView(b,lp);}

    void setupAccounts(){String sel=accountSpin.getSelectedItem()==null?"전체":accountSpin.getSelectedItem().toString(); LinkedHashSet<String> set=new LinkedHashSet<>(); set.add("전체"); for(Holding h:holdings)set.add(clean(h.account)); ArrayList<String> a=new ArrayList<>(set); ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,a); ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); accountSpin.setAdapter(ad); int i=a.indexOf(sel); accountSpin.setSelection(i>=0?i:0); accountSpin.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){refreshNumbers();} public void onNothingSelected(android.widget.AdapterView<?> p){refreshNumbers();}});}
    List<Holding> filtered(){String sel=accountSpin==null||accountSpin.getSelectedItem()==null?"전체":accountSpin.getSelectedItem().toString(); ArrayList<Holding> out=new ArrayList<>(); for(Holding h:holdings)if("전체".equals(sel)||sel.equals(clean(h.account)))out.add(h); return out;}
    void refreshNumbers(){if(valueView==null)return; List<Holding> list=filtered(); double cost=0,val=0,tg=0; for(Holding h:list){cost+=disp(h.cost(),h.cur); val+=disp(h.value(),h.cur); tg+=Math.max(0,h.target);} double pnl=val-cost, rate=cost==0?0:pnl/cost*100; valueView.setText(money(val)); costView.setText(money(cost)); pnlView.setText((pnl>=0?"+":"")+money(pnl)); pnlView.setTextColor(pnl>=0?RED:LOSS); rateView.setText(String.format(Locale.KOREA,"%+.2f%%",rate)); rateView.setTextColor(rate>=0?RED:LOSS); fxView.setText("1달러 = "+won.format(usdKrw)+"원"); targetView.setText(tg>0?String.format(Locale.KOREA,"%.1f%%",tg):"목표비중 미설정"); rebalanceView.setText(summary(list,val)); if(chart!=null){chart.currency=displayCurrency; chart.fx=usdKrw; chart.setData(list);} renderTable(list,val);}
    String summary(List<Holding> list,double total){if(total<=0)return "데이터 없음"; double buy=0,sell=0; for(Holding h:list)if(h.target>0){double diff=total*h.target/100-disp(h.value(),h.cur); if(diff>0)buy+=diff; else sell+=-diff;} if(buy+sell==0)return "목표비중을 설정하면 자동 계산"; return "추가매수 "+money(buy)+" / 축소 "+money(sell);}
    void renderTable(List<Holding> list,double total){if(table==null)return; table.removeAllViews(); String[] hs={"계좌","코드","종목","통화","수량","현재가","평가","손익","현재%","목표%","조정","분배시기","삭제"}; TableRow head=new TableRow(this); for(String h:hs)cell(head,h,true,TEXT); table.addView(head); for(Holding h:list){TableRow r=new TableRow(this); double v=disp(h.value(),h.cur), p=disp(h.pnl(),h.cur), pct=total==0?0:v/total*100, adj=h.target>0?total*h.target/100-v:0; cell(r,clean(h.account),false,TEXT);cell(r,h.code,false,TEXT);cell(r,h.name,false,TEXT);cell(r,h.cur,false,TEXT);cell(r,qty(h.qty),false,TEXT);cell(r,price(h.now,h.cur),false,TEXT);cell(r,money(v),false,TEXT);cell(r,(p>=0?"+":"")+money(p),false,p>=0?RED:LOSS);cell(r,String.format(Locale.KOREA,"%.1f%%",pct),false,TEXT);cell(r,h.target>0?String.format(Locale.KOREA,"%.1f%%",h.target):"-",false,TEXT);cell(r,h.target>0?(adj>=0?"+":"")+money(adj):"-",false,adj>=0?RED:LOSS);cell(r,shorten(h.memo),false,TEXT); Button del=new Button(this); del.setText("삭제"); del.setOnClickListener(vv->{holdings.remove(h); saveData(); render();}); r.addView(del); table.addView(r);}}
    void cell(TableRow r,String s,boolean b,int color){TextView v=txt(s==null?"":s,b?13:12,color,b); v.setPadding(dp(8),dp(8),dp(8),dp(8)); v.setMinWidth(dp(82)); r.addView(v);}

    void addDialog(){LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); EditText account=input("계좌명 예: ISA",false); Spinner sp=new Spinner(this); ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,labels()); ad.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); sp.setAdapter(ad); TextView info=txt(CATALOG[0].label(),13,TEXT,true); EditText qty=input("수량",true), buy=input("평균매입가",true), now=input("현재가",true), target=input("목표비중 %",true), memo=input("자금분배시기 메모",false); memo.setSingleLine(false); memo.setMinLines(2); sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){Stock it=CATALOG[pos]; info.setText(it.label()); if(CASH.equals(it.code)){if(now.length()==0)now.setText("1"); if(buy.length()==0)buy.setText("1");}} public void onNothingSelected(android.widget.AdapterView<?> p){}}); box.addView(account); box.addView(sp,new LinearLayout.LayoutParams(-1,dp(48))); box.addView(info); box.addView(qty); box.addView(buy); box.addView(now); box.addView(target); box.addView(memo); Button price=new Button(this); price.setText("선택 종목 현재가 가져오기"); price.setOnClickListener(v->{Stock it=CATALOG[sp.getSelectedItemPosition()]; fetchOne(it,now,buy);}); box.addView(price); new AlertDialog.Builder(this).setTitle("종목 선택 추가").setView(box).setPositiveButton("저장",(d,w)->{Stock it=CATALOG[sp.getSelectedItemPosition()]; double n=num(now), b=num(buy); if(b==0&&n>0)b=n; holdings.add(new Holding(val(account,"기본계좌"),it.code,it.name,num(qty),b,n,it.cur,num(target),val(memo,""))); saveData(); render();}).setNegativeButton("취소",null).show();}
    void fetchOne(Stock it,EditText now,EditText buy){if(CASH.equals(it.code)){now.setText("1"); if(buy.length()==0)buy.setText("1"); return;} toast("조회 중"); new Thread(()->{double p=fetchPrice(it.code); runOnUiThread(()->{if(p>0){now.setText(plain(p)); if(buy.length()==0)buy.setText(plain(p)); toast("현재가 반영");} else toast("조회 실패");});}).start();}
    void allocationDialog(){ScrollView sv=new ScrollView(this); LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); sv.addView(box); ArrayList<EditText> ps=new ArrayList<>(), ms=new ArrayList<>(); for(Holding h:holdings){box.addView(txt(h.name+" / "+h.code,14,TEXT,true)); EditText p=input("목표비중 %",true); if(h.target>0)p.setText(plain(h.target)); EditText m=input("자금분배시기",false); m.setSingleLine(false); m.setMinLines(2); m.setText(h.memo); box.addView(p); box.addView(m); ps.add(p); ms.add(m);} new AlertDialog.Builder(this).setTitle("비율/자금분배 조정").setView(sv).setPositiveButton("저장",(d,w)->{for(int i=0;i<holdings.size();i++){holdings.get(i).target=num(ps.get(i)); holdings.get(i).memo=ms.get(i).getText().toString().trim();} saveData(); render();}).setNegativeButton("취소",null).show();}
    void aiDialog(){LinearLayout box=new LinearLayout(this); box.setOrientation(LinearLayout.VERTICAL); box.setPadding(dp(12),0,dp(12),0); box.addView(txt("AI 답변을 붙여넣으세요. 예: AAPL / 25% / 지금 30%, 조정 시 40%",12,MUTED,false)); EditText e=input("AI 추천 내용",false); e.setSingleLine(false); e.setMinLines(9); box.addView(e); new AlertDialog.Builder(this).setTitle("AI 추천 적용").setView(box).setPositiveButton("적용",(d,w)->applyAi(e.getText().toString())).setNegativeButton("취소",null).show();}
    void applyAi(String text){int n=0; for(String line:text.split("\\n")){double pct=findPct(line); if(pct<0)continue; Stock s=findStock(line); if(s==null)continue; Holding h=findHolding(s.code); if(h==null){h=new Holding("AI추천",s.code,s.name,0,0,CASH.equals(s.code)?1:0,s.cur,pct,line); holdings.add(h);} else {h.target=pct; h.memo=line; h.name=s.name; h.cur=s.cur;} n++;} saveData(); render(); toast(n+"개 항목 반영");}
    void copyAiPrompt(){StringBuilder sb=new StringBuilder(); sb.append("아래 포트폴리오를 현재 시장상황에 맞게 목표비중과 자금 분배시기로 재구성해 줘. 각 줄은 '티커 또는 종목명 / 목표비중% / 자금분배시기' 형식으로 작성.\n"); sb.append("표시통화 ").append(displayCurrency).append(" USD/KRW ").append(usdKrw).append("\n"); double total=0; for(Holding h:holdings)total+=disp(h.value(),h.cur); for(Holding h:holdings)sb.append(h.code).append(" / ").append(h.name).append(" / 현재비중 ").append(total==0?"0%":String.format(Locale.KOREA,"%.1f%%",disp(h.value(),h.cur)/total*100)).append(" / 목표 ").append(h.target>0?plain(h.target)+"%":"미설정").append("\n"); ((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("AI portfolio prompt",sb.toString())); toast("AI 요청문 복사 완료");}

    void refreshMarket(){toast("자동 갱신 중"); new Thread(()->{int ok=0; double fx=fetchFx(); if(fx>0)usdKrw=fx; for(Holding h:holdings){if(h.code==null||h.code.length()==0||CASH.equals(h.code))continue; double p=fetchPrice(h.code); if(p>0){h.now=p; if(h.buy==0)h.buy=p; ok++;}} int count=ok; runOnUiThread(()->{saveSettings(); saveData(); render(); toast("현재가 "+count+"개와 환율 갱신 완료");});}).start();}
    double fetchFx(){try{String j=fetch("https://open.er-api.com/v6/latest/USD"); JSONObject r=new JSONObject(j).optJSONObject("rates"); return r==null?0:r.optDouble("KRW",0);}catch(Exception e){return 0;}}
    double fetchPrice(String sym){try{String u="https://query1.finance.yahoo.com/v8/finance/chart/"+URLEncoder.encode(sym,"UTF-8")+"?range=1d&interval=1d"; JSONObject meta=new JSONObject(fetch(u)).getJSONObject("chart").getJSONArray("result").getJSONObject(0).getJSONObject("meta"); double p=meta.optDouble("regularMarketPrice",0); return p>0?p:meta.optDouble("previousClose",0);}catch(Exception e){return 0;}}
    String fetch(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection(); c.setConnectTimeout(8000); c.setReadTimeout(8000); c.setRequestProperty("User-Agent","Mozilla/5.0"); BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8")); StringBuilder sb=new StringBuilder(); String line; while((line=br.readLine())!=null)sb.append(line); br.close(); return sb.toString();}

    void importCsv(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("*/*"); startActivityForResult(i,REQ_IMPORT);} void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("text/csv"); i.putExtra(Intent.EXTRA_TITLE,"portfolio.csv"); startActivityForResult(i,REQ_EXPORT);} public void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data); if(res!=RESULT_OK||data==null||data.getData()==null)return; try{if(req==REQ_IMPORT){parseCsv(data.getData()); saveData(); render(); toast("CSV 가져오기 완료");}else if(req==REQ_EXPORT){OutputStream o=getContentResolver().openOutputStream(data.getData()); o.write(csvText().getBytes("UTF-8")); o.close(); toast("CSV 저장 완료");}}catch(Exception e){toast("처리 실패: "+e.getMessage());}}
    void parseCsv(Uri uri)throws Exception{BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(uri),"UTF-8")); ArrayList<String[]> rows=new ArrayList<>(); String line; while((line=br.readLine())!=null)if(line.trim().length()>0)rows.add(split(line)); br.close(); if(rows.isEmpty())return; int start=0,acc=0,code=1,name=2,qty=3,buy=4,now=5,cur=-1,tgt=-1,memo=-1; if(join(rows.get(0)).contains("종목")||join(rows.get(0)).toLowerCase(Locale.ROOT).contains("account")){String[] h=rows.get(0); acc=find(h,"계좌","account"); code=find(h,"종목코드","코드","ticker","symbol"); name=find(h,"종목명","이름","name"); qty=find(h,"수량","qty"); buy=find(h,"평균","평단","매입","buy"); now=find(h,"현재","price","now"); cur=findOpt(h,"통화","currency"); tgt=findOpt(h,"목표","target"); memo=findOpt(h,"분배","memo","plan"); start=1;} ArrayList<Holding> im=new ArrayList<>(); for(int i=start;i<rows.size();i++){String[] r=rows.get(i); String c=get(r,code,""), n=get(r,name,c); if(c.length()==0&&n.length()==0)continue; im.add(new Holding(get(r,acc,"기본계좌"),c,n,number(get(r,qty,"0")),number(get(r,buy,"0")),number(get(r,now,"0")),get(r,cur,infer(c)),number(get(r,tgt,"0")),get(r,memo,"")));} holdings.clear(); holdings.addAll(im);} 
    String csvText(){StringBuilder sb=new StringBuilder("계좌,종목코드,종목명,통화,수량,평균매입가,현재가,평가금액,손익,수익률,목표비중,분배시기\n"); for(Holding h:holdings)sb.append(q(h.account)).append(',').append(q(h.code)).append(',').append(q(h.name)).append(',').append(q(h.cur)).append(',').append(h.qty).append(',').append(h.buy).append(',').append(h.now).append(',').append(disp(h.value(),h.cur)).append(',').append(disp(h.pnl(),h.cur)).append(',').append(h.rate()).append(',').append(h.target).append(',').append(q(h.memo)).append('\n'); return sb.toString();}
    String[] split(String line){ArrayList<String> out=new ArrayList<>(); StringBuilder sb=new StringBuilder(); boolean q=false; for(int i=0;i<line.length();i++){char c=line.charAt(i); if(c=='\"')q=!q; else if(c==','&&!q){out.add(sb.toString().trim()); sb.setLength(0);} else sb.append(c);} out.add(sb.toString().trim()); return out.toArray(new String[0]);}

    void saveData(){try{JSONArray a=new JSONArray(); for(Holding h:holdings){JSONObject o=new JSONObject(); o.put("account",h.account);o.put("code",h.code);o.put("name",h.name);o.put("qty",h.qty);o.put("buy",h.buy);o.put("now",h.now);o.put("cur",h.cur);o.put("target",h.target);o.put("memo",h.memo); a.put(o);} getSharedPreferences("data",0).edit().putString("holdings",a.toString()).apply();}catch(Exception e){}}
    void loadData(){try{JSONArray a=new JSONArray(getSharedPreferences("data",0).getString("holdings","[]")); for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i); holdings.add(new Holding(o.optString("account"),o.optString("code"),o.optString("name"),o.optDouble("qty"),o.optDouble("buy"),o.optDouble("now"),o.optString("cur",infer(o.optString("code"))),o.optDouble("target"),o.optString("memo")));}}catch(Exception e){}}
    void saveSettings(){getSharedPreferences("settings",0).edit().putString("display",displayCurrency).putFloat("fx",(float)usdKrw).apply();} void loadSettings(){SharedPreferences s=getSharedPreferences("settings",0); displayCurrency=s.getString("display",KRW); usdKrw=s.getFloat("fx",1400f);} void sample(){holdings.add(new Holding("ISA","005930.KS","삼성전자",10,70000,72500,KRW,30,"조정 시 분할매수")); holdings.add(new Holding("연금","360750.KS","TIGER 미국S&P500",20,20000,21000,KRW,25,"월 1회 적립")); holdings.add(new Holding("해외","AAPL","Apple",2,180,192,USD,25,"환율 하락 시 추가")); holdings.add(new Holding("현금","CASH","현금",1000000,1,1,KRW,20,"예비자금"));}
    void confirmReset(){new AlertDialog.Builder(this).setTitle("전체 초기화").setMessage("모든 보유종목을 삭제할까요?").setPositiveButton("삭제",(d,w)->{holdings.clear(); saveData(); render();}).setNegativeButton("취소",null).show();}

    TextView txt(String s,int size,int color,boolean bold){TextView v=new TextView(this); v.setText(s); v.setTextSize(size); v.setTextColor(color); if(bold)v.setTypeface(null,1); return v;} EditText input(String hint,boolean n){EditText e=new EditText(this); e.setHint(hint); if(n)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED); return e;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable(); g.setColor(c); g.setCornerRadius(dp(r)); return g;} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    double num(EditText e){return number(e.getText().toString());} double number(String s){try{return Double.parseDouble(s.replace(",","").replace("원","").replace("₩","").replace("$","").replace("%","").trim());}catch(Exception e){return 0;}} String val(EditText e,String f){String s=e.getText().toString().trim(); return s.length()==0?f:s;} String clean(String s){return s==null||s.trim().length()==0?"기본계좌":s.trim();} String qty(double d){return d==Math.rint(d)?String.valueOf((long)d):plain(d);} String plain(double d){return d==Math.rint(d)?String.valueOf((long)d):String.format(Locale.US,"%.4f",d).replaceAll("0+$","").replaceAll("\\.$","");} String money(double a){return USD.equals(displayCurrency)?"$"+dollar.format(a):won.format(Math.round(a))+"원";} String price(double a,String c){return USD.equals(c)?"$"+dollar.format(a):won.format(Math.round(a))+"원";} double disp(double a,String from){if(from==null)from=KRW; if(from.equals(displayCurrency))return a; if(USD.equals(from)&&KRW.equals(displayCurrency))return a*usdKrw; if(KRW.equals(from)&&USD.equals(displayCurrency))return usdKrw<=0?a:a/usdKrw; return a;} String shorten(String s){if(s==null||s.trim().length()==0)return "-"; s=s.replace('\n',' ').trim(); return s.length()>24?s.substring(0,24)+"…":s;} static String infer(String c){if(c==null)return KRW; c=c.toUpperCase(Locale.ROOT); return c.endsWith(".KS")||c.endsWith(".KQ")||c.matches("\\d{6}")||CASH.equals(c)?KRW:USD;} static String norm(String s){return s==null?"":s.toUpperCase(Locale.ROOT).replace(" ","").replace(".","").replace("-","").replace("/","");}
    String[] labels(){String[] l=new String[CATALOG.length]; for(int i=0;i<CATALOG.length;i++)l[i]=CATALOG[i].label(); return l;} Holding findHolding(String code){String n=norm(code); for(Holding h:holdings)if(norm(h.code).equals(n))return h; return null;} Stock findStock(String line){String n=norm(line); for(Stock s:CATALOG)if(n.contains(norm(s.code))||n.contains(norm(s.name)))return s; return null;} double findPct(String line){Matcher m=Pattern.compile("(\\d+(?:\\.\\d+)?)\\s*%").matcher(line); return m.find()?number(m.group(1)):-1;} int find(String[] h,String...k){int i=findOpt(h,k); return i>=0?i:0;} int findOpt(String[] h,String...k){for(int i=0;i<h.length;i++){String s=h[i].replace(" ","").toLowerCase(Locale.ROOT); for(String x:k)if(s.contains(x.toLowerCase(Locale.ROOT)))return i;} return -1;} String get(String[] a,int i,String f){return i>=0&&i<a.length&&a[i].trim().length()>0?a[i].trim():f;} String join(String[] a){StringBuilder b=new StringBuilder(); for(String s:a)b.append(s); return b.toString();} String q(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}

    public static class Chart extends View{Paint p=new Paint(1); ArrayList<Holding> data=new ArrayList<>(); int[] colors={Color.rgb(66,133,244),Color.rgb(251,188,5),Color.rgb(52,168,83),Color.rgb(156,39,176),Color.rgb(0,150,136),Color.rgb(255,112,67)}; String currency=KRW; double fx=1400; public Chart(Context c){super(c); setPadding(10,10,10,10);} void setData(List<Holding> l){data.clear(); data.addAll(l); invalidate();} protected void onDraw(Canvas c){int w=getWidth(),h=getHeight(); p.setColor(Color.WHITE); c.drawRect(0,0,w,h,p); p.setColor(TEXT); p.setTextSize(30); p.setFakeBoldText(true); c.drawText("자산 비중",24,44,p); p.setFakeBoldText(false); double total=0; for(Holding x:data)total+=Math.max(0,val(x)); if(total<=0){p.setColor(MUTED); c.drawText("데이터 없음",30,95,p); return;} float cx=w*.28f,cy=h*.30f,r=Math.min(w,h)*.18f,start=-90; RectF oval=new RectF(cx-r,cy-r,cx+r,cy+r); for(int i=0;i<data.size();i++){float sw=(float)(Math.max(0,val(data.get(i)))/total*360); p.setColor(colors[i%colors.length]); c.drawArc(oval,start,sw,true,p); start+=sw;} p.setColor(Color.WHITE); c.drawCircle(cx,cy,r*.58f,p); int y=78; p.setTextSize(18); for(int i=0;i<Math.min(data.size(),6);i++){Holding x=data.get(i); p.setColor(colors[i%colors.length]); c.drawRoundRect(w*.56f,y-16,w*.56f+22,y+5,6,6,p); p.setColor(Color.rgb(70,75,85)); c.drawText(shortName(x.name)+" "+String.format(Locale.KOREA,"%.1f%%",val(x)/total*100),w*.56f+30,y+3,p); y+=30;} float top=h*.60f,base=h-52,left=34,right=w-34; p.setTextSize(28); p.setColor(TEXT); p.setFakeBoldText(true); c.drawText("종목별 손익",24,top-18,p); p.setFakeBoldText(false); double max=1; for(Holding x:data)max=Math.max(max,Math.abs(pnl(x))); int n=Math.min(data.size(),8); float gap=8,bw=(right-left-gap*(n-1))/Math.max(1,n); p.setColor(Color.rgb(225,229,236)); c.drawLine(left,base,right,base,p); for(int i=0;i<n;i++){Holding x=data.get(i); float bh=(float)(Math.abs(pnl(x))/max*(h*.20f)),x0=left+i*(bw+gap); p.setColor(pnl(x)>=0?RED:LOSS); c.drawRoundRect(x0,base-bh,x0+bw,base,8,8,p); p.setColor(Color.rgb(70,75,85)); p.setTextSize(16); c.drawText(shortName(x.name),x0,base+24,p);}} double val(Holding h){if(h.cur.equals(currency))return h.value(); if(USD.equals(h.cur)&&KRW.equals(currency))return h.value()*fx; if(KRW.equals(h.cur)&&USD.equals(currency))return h.value()/fx; return h.value();} double pnl(Holding h){if(h.cur.equals(currency))return h.pnl(); if(USD.equals(h.cur)&&KRW.equals(currency))return h.pnl()*fx; if(KRW.equals(h.cur)&&USD.equals(currency))return h.pnl()/fx; return h.pnl();} static String shortName(String s){return s==null?"":s.length()>5?s.substring(0,5):s;}}
}
